spring:
  profiles:
    active:
    - dev
---
server:
  port: 8020
spring:
  profiles: dev    #开发环境
  zipkin:
    base-url: http://localhost:9411
  application:
    name: product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
version: springcloud version 1.0
---
server:
  port: 8021
spring:
  profiles: test    #测试环境
  zipkin:
    base-url: http://localhost:9411
  application:
    name: product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
version: springcloud version 1.0